model: /home/catkin_ws/projects/clip_sam_ws/CLIP-ViT-B-32-laion2B-s34B-b79K/_ggml-model-f32.gguf
# model: /home/catkin_ws/projects/clip_sam_ws/CLIP-ViT-B-32-laion2B-s34B-b79K/_ggml-model-f16.gguf
# model: /home/catkin_ws/projects/clip_sam_ws/CLIP-ViT-H-14-laion2B-s32B-b79K/_ggml-model-f32.gguf
threads: 4
verbose: 1
text: "table"
image: "/home/catkin_ws/projects/clip_sam_ws/SamToClip/test_images/frame0098.jpg"